#############################################################################
# Makefile for building: bin/QMSD
# Generated by qmake (2.01a) (Qt 4.7.0) on: ?? ????. 6 18:21:25 2011
# Project:  QMSD.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile QMSD.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Iobj -Iobj
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp \
		src/mediasitedownloder.cpp obj/moc_mediasitedownloder.cpp \
		qrc_qmsd_main.cpp
OBJECTS       = obj/main.o \
		obj/mediasitedownloder.o \
		obj/moc_mediasitedownloder.o \
		obj/qrc_qmsd_main.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		QMSD.pro
QMAKE_TARGET  = QMSD
DESTDIR       = bin/
TARGET        = bin/QMSD

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): obj/ui_mediasitedownloder.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QMSD.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile QMSD.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile QMSD.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/QMSD1.0.0 || $(MKDIR) obj/QMSD1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/QMSD1.0.0/ && $(COPY_FILE) --parents headers/mediasitedownloder.h obj/QMSD1.0.0/ && $(COPY_FILE) --parents resource/qmsd_main.qrc obj/QMSD1.0.0/ && $(COPY_FILE) --parents main.cpp src/mediasitedownloder.cpp obj/QMSD1.0.0/ && $(COPY_FILE) --parents ui/mediasitedownloder.ui obj/QMSD1.0.0/ && $(COPY_FILE) --parents lang/qmsd_ru.ts lang/qmsd_def.ts lang/qmsd_en.ts obj/QMSD1.0.0/ && (cd `dirname obj/QMSD1.0.0` && $(TAR) QMSD1.0.0.tar QMSD1.0.0 && $(COMPRESS) QMSD1.0.0.tar) && $(MOVE) `dirname obj/QMSD1.0.0`/QMSD1.0.0.tar.gz . && $(DEL_FILE) -r obj/QMSD1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: obj/moc_mediasitedownloder.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_mediasitedownloder.cpp
obj/moc_mediasitedownloder.cpp: headers/mediasitedownloder.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/mediasitedownloder.h -o obj/moc_mediasitedownloder.cpp

compiler_rcc_make_all: qrc_qmsd_main.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qmsd_main.cpp
qrc_qmsd_main.cpp: resource/qmsd_main.qrc \
		resource/main.png \
		resource/Symbol-Delete.png \
		resource/gtranslator.png \
		resource/Symbol-Restricted.png \
		resource/Arrow-Up.png \
		resource/Arrow-Left.png \
		resource/Arrow-Right.png \
		resource/Symbol-Add.png \
		resource/evolution-tasks.png \
		resource/Arrow-Down.png
	/usr/bin/rcc -name qmsd_main resource/qmsd_main.qrc -o qrc_qmsd_main.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: obj/ui_mediasitedownloder.h
compiler_uic_clean:
	-$(DEL_FILE) obj/ui_mediasitedownloder.h
obj/ui_mediasitedownloder.h: ui/mediasitedownloder.ui
	/usr/bin/uic-qt4 ui/mediasitedownloder.ui -o obj/ui_mediasitedownloder.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

obj/main.o: main.cpp headers/mediasitedownloder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/mediasitedownloder.o: src/mediasitedownloder.cpp headers/mediasitedownloder.h \
		obj/ui_mediasitedownloder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mediasitedownloder.o src/mediasitedownloder.cpp

obj/moc_mediasitedownloder.o: obj/moc_mediasitedownloder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mediasitedownloder.o obj/moc_mediasitedownloder.cpp

obj/qrc_qmsd_main.o: qrc_qmsd_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_qmsd_main.o qrc_qmsd_main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

